FROM node:20-alpine

WORKDIR /app

# 先只複製 package.json，讓 npm install 可以被 cache
COPY package*.json ./
RUN apk add --no-cache openssl

RUN npm install

# 實際 code 來自 volume mount，不需要 COPY src
EXPOSE 3000

CMD ["npx", "tsx", "watch", "src/index.ts"]
