FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma
RUN apk add --no-cache openssl

RUN npm install

CMD ["sh", "-c", "echo 'Set a service command in docker compose'; tail -f /dev/null"]
