import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    coverage: {
      // all: false,
      include: ['services/**/*.ts', 'packages/**/*.ts'],
      exclude: [
        'packages/shared-types/**',
        'packages/shared-db/**',
        'packages/shared-nats/**',
        'packages/shared-redis/src/redis.ts',
        'packages/shared-redis/src/presence.ts',
        'packages/shared-redis/src/fake-redis.ts',
        'packages/shared-redis/src/index.ts',
        'services/user-service/**/*.service.ts',
        'services/**/*.repository.ts',
        'services/message-writer-service/src/main.ts',
        'services/realtime-service/src/modules/realtime/realtime.service.ts',
        'services/realtime-service/src/modules/realtime/realtime.server.ts',
        'services/realtime-service/src/modules/realtime/presence.store.ts',
        'services/realtime-service/src/modules/realtime/realtime.types.ts',
        'services/*/src/app.ts',
        '**/index.ts',
        '**/*.test.ts',
        '**/*.spec.ts',
        '**/__tests__/**',
        '**/main.ts',
        'tests/**',
        'scripts/**',
      ],
      provider: 'v8',
      reporter: ['text', 'json', 'json-summary', 'lcov'],
      reportsDirectory: 'coverage/unit',
      thresholds: {
        branches: 35,
        functions: 45,
        lines: 45,
        statements: 45,
      },
    },
    environment: 'node',
    include: ['services/**/*.unit.test.ts', 'packages/**/*.unit.test.ts'],
    setupFiles: ['./tests/helpers/integration-env.cjs'],
  },
});
